language: android

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Kotlin binding staleness check.
  - ./gradlew generateKotlin
  - if [ ! -z "$(git status --porcelain)" ]; then echo "Bindings changed. Did you run 'generateKotlin'?"; exit 1; fi
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-18;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew ":$MODULE:assemble" ":$MODULE-kotlin:assemble" --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew ":$MODULE:build" ":$MODULE-kotlin:build" ":$MODULE:connectedCheck" --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  matrix:
    - MODULE=rxbinding
    - MODULE=rxbinding-appcompat-v7
    - MODULE=rxbinding-design
    - MODULE=rxbinding-leanback-v17
    - MODULE=rxbinding-recyclerview-v7
    - MODULE=rxbinding-support-v4
  global:
    - secure: "kgsT0j2b0GYbQjrDSdIYoh9lXOb2bAqA8gOx7ipegYLiNUuAjTeclw/3IFd5WpPNEhwTvDlb8Pwi/GYsXwYLdjysZUsj73a027swKAuXRBEjnBpfcvhEwKdoO5Ygoz/uH7TvcuCKzEz/bRKIglvn9PcTrzIHHZZIXa/mLU5otNE="
    - secure: "XNvNiKfh2+JAHvbj7/jtaHKcu5FlN0fHwKwiDZYiCkTkG4kXsKlGtbQX4uk/RU4ZEe3pCPt1I6u66e5c57SLiDNMI0dnjdmSWL6Pcd1CoJVagYYq48TNgQARRe1zntXZvweRmqbfnsQiX5neLwaDj+UNM1yq6D3h2quPVrgoBBM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
